### ISSUE TITLE
Ensure prettier runs on new code

### ISSUE THREAD

**Issue by foreverhomes** [leibovic/baby-in-tow#19]
Couple ways we could do this:

1. Have these steps run as part of CI
2. A pre-commit hook using [husky](https://github.com/typicode/husky) (this might also be a good spot to add linting

**Comment by leibovic** [comment]
Yeah, I think it makes sense to run as a pre-commit hook so that people get feedback as early as possible. Gavin suggests using lint-staged and now wants to take this issue, haha.
