### ISSUE TITLE
`npm install` broken on `@goproperly/eslint-config-properly-react` step

### ISSUE THREAD

**Issue by foreverhomes** [leibovic/baby-in-tow#22]
After pulling latest dev, I'm not able to run `npm install` successfully. 

<img width="889" alt="Screen Shot 2019-12-27 at 4 09 53 PM" src="https://user-images.githubusercontent.com/2057384/71532993-4dab6280-28c4-11ea-949d-963a0cb0658d.png">

`
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@goproperly%2feslint-config-properly-react - Not found
npm ERR! 404 
npm ERR! 404  '@goproperly/eslint-config-properly-react@2.0.11' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'baby-in-tow'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jdebutte/.npm/_logs/2019-12-27T21_08_10_495Z-debug.log
`

**Comment by gavinsharp** [comment]
It might be an authentication issue, try this:
https://help.github.com/en/github/managing-packages-with-github-packages/configuring-npm-for-use-with-github-packages#authenticating-to-github-packages

I will update the README assuming that works!

**Comment by gavinsharp** [comment]
Oh wait, that's not it. From the log message, it appears to be looking for `@goproperly/eslint-config-properly-react` in the NPM registry. That's odd - the `.npmrc` should be pointing `npm` to the GitHub registry.

Can you confirm the `.npmrc` is there locally?

**Comment by gavinsharp** [comment]
It appears that the `.npmrc` is not taking effect for you for some reason.

For me locally, when the `.npmrc` does take effect, it breaks in a different way (as a result of 529586d1f55296450b7c1988e0d8543423642ec5 from #21):
```
gavin-properly:baby-in-tow gavin$ npm i
Error: Failed to replace env in config: ${NODE_AUTH_TOKEN}
```

I will try to find a solution for that.
